title: datakorn
description: Monthly reflections on the state of data visualization. Founded June 2017 in Berlin.
baseurl: ""
url: "http://datakorn.com"
lang: en

markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

members:
  - name: Christian Laesser
    url: https://christianlaesser.com/
  - name: Jonas Parnow
    url: http://jonasparnow.de
  - name: Kim Albrecht
    url: http://www.kimalbrecht.com
  - name: Paul Heinicker
    url: http://www.paulheinicker.com
  - name: Sebastian Sadowski
    url: https://datadesign.studio/
