title: datakorn
description: Monthly reflections on the state of data visualization. Founded June 2017 in Berlin.
baseurl: ""
url: "http://datakorn.com"
lang: en

markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

members:
  - name: Christian Laesser
    url: https://christianlaesser.com/
  - name: Jonas Parnow
    url: http://jonasparnow.de
  - name: Kim Albrecht
    url: http://www.kimalbrecht.com
  - name: Paul Heinicker
    url: http://www.paulheinicker.com
  - name: Sebastian Sadowski
    url: https://datadesign.studio/

content:
  - number: 1
    date: 2017-06-15
    topic: Punkt und Linie
    organiser: Paul H.
    location:
      label: Bier Lounge
      link: http://www.google.de
    source:
      label: Kittler
      link: http://www.google.de
    description: You have not engaged in our great and gathering conversation, nor did you create the wealth of our marketplaces. You do not know our culture, our ethics, or the unwritten codes that already provide our society more order than could be obtained by any of your impositions.
    members:
      - Christian Laesser
      - Jonas Parnow
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 2
    date: 2017-07-20
    topic: Vier Ebenen der Daten Visualisierung
    organiser: Paul H.
    location:
      label: Metzer Eck
      link: https://www.metzer-eck.de/
    source:
      label: Gottfried Jäger
      link: http://www.google.de
    description: You have not engaged in our great and gathering conversation, nor did you create the wealth of our marketplaces. You do not know our culture, our ethics, or the unwritten codes that already provide our society more order than could be obtained by any of your impositions.
    members:
      - Christian Laesser
      - Jonas Parnow
      - Kim Albrecht
      - Paul Heinicker
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 3
    date: 2017-08-31
    topic: Virtual Reality
    organiser: Sebastian Sadowski
    location:
      label: Nachtigall Bar
      link: https://www.facebook.com/nachtigallbarberlin/
    source:
      label: Data Analytics in Virtual Reality… Because Why Not?
      link: https://m.youtube.com/watch?v=u76ww3NJFgE
    description: You have not engaged in our great and gathering conversation, nor did you create the wealth of our marketplaces. You do not know our culture, our ethics, or the unwritten codes that already provide our society more order than could be obtained by any of your impositions.
    members:
      - Christian Laesser
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 4
    date: 2017-09-26
    topic: Informationsgestaltung zwischen Ästhetik und Verantwortung
    organiser: Christian L.
    location:
      label: Berliner Bürgerstuben
      link: http://www.die-stargarder.de/berliner-buergerstuben/
    source:
      label: Kittler
      link: http://www.google.de
    description: Produziert unsere Szene zuviel Dataporn und vergisst dabei das eigentliche Ziel? Das wäre Informationen zu vermitteln und Aktionen mit einem wirklichen Mehrwert zu ermöglichen/anzuregen?
    members:
      - Christian Laesser
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 5
    date: 2017-09-26
    topic: Informationsgestaltung zwischen Ästhetik und Verantwortung
    organiser: Christian L.
    location:
      label: Berliner Bürgerstuben
      link: http://www.die-stargarder.de/berliner-buergerstuben/
    source:
      label: Kittler
      link: http://www.google.de
    description: Produziert unsere Szene zuviel Dataporn und vergisst dabei das eigentliche Ziel? Das wäre Informationen zu vermitteln und Aktionen mit einem wirklichen Mehrwert zu ermöglichen/anzuregen?
    members:
      - Christian Laesser
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 6
    date: 2017-10-19
    topic: Hijacking Minds
    organiser: Jonas P
    location:
      label: Zum Schusterjungen
      link: http://www.zumschusterjungen.com/
    source:
      label: "Our minds can be hijacked: the tech insiders who fear a smartphone dystopia"
      link: https://www.theguardian.com/technology/2017/oct/05/smartphone-addiction-silicon-valley-dystopia
    description: Produziert unsere Szene zuviel Dataporn und vergisst dabei das eigentliche Ziel? Das wäre Informationen zu vermitteln und Aktionen mit einem wirklichen Mehrwert zu ermöglichen/anzuregen?
    members:
      - Christian Laesser
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
      - Jonas Parnow
    guest:
      label: Jonas
      link: http://www.jonasparnow.de
  - number: 6
    date: 2017-11-07
    topic: Hijacking Minds
    organiser: Kim A.
    location:
      label: Oberwasser
      link: http://www.oberwasser-berlin.de/
    source:
      label: Niklas Luhmann – Das Medium der Kunst
      link: https://www.reclam.de/detail/978-3-15-018149-2/Luhmann__Niklas/Aufsaetze_und_Redensmartphone-addiction-silicon-valley-dystopia
    description: Produziert unsere Szene zuviel Dataporn und vergisst dabei das eigentliche Ziel? Das wäre Informationen zu vermitteln und Aktionen mit einem wirklichen Mehrwert zu ermöglichen/anzuregen?
    members:
      - Christian Laesser
      - Kim Albrecht
      - Paul Heinicker
      - Sebastian Sadowski
      - Jonas Parnow
    guest:
      label: Jonas
      link: http://www.jonasparnow.de